services:
  - type: web
    name: airline-feedback-system
    env: docker
    dockerfilePath: Dockerfile
    plan: free

    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
